### ISSUE TITLE
Seems no need to return unsubscribe

### ISSUE THREAD

**Issue by bendwarn** [kazuooooo/pinia-plugin-firestore-sync#6]
Serve as property instead. Because if multiple component called sync at the same time, there will be duplicate listener or overwrite reference. 

Benefit:
- sync can check this property before calling onSnapshot
- send to onScopeDispose internally, no need to handle by outside

**Comment by kazuooooo** [comment]
Hi, thank you for reporting.

# Returning Unsubscribe

I think `sync` function needs to return `Unsbscribe`,  so that users can stop the subscription by themselves.

>  there will be duplicate listener or overwrite reference.
I've experimented with this.
If two sync functions are called to the same document, and call unsubscribe of one.

store
```ts
import {
  doc, getFirestore, Unsubscribe
} from 'firebase/firestore'
import { defineStore } from 'pinia'
export type State = {
  a: { value: string | null }
  b: { value: string | null },
  unsubscribeOfA: Unsubscribe | null
}

export const useTestStore = defineStore('test', {
  state: (): State => {
    return {
      a: { value: null },
      b: { value: null },
      unsubscribeOfA: null
    }
  },
  actions: {
    setup() {
      const store = getFirestore()
      this.unsubscribeOfA = this.sync('a', doc(store, 'Foo/bar'))
      this.sync('b', doc(store, 'Foo/bar'))
    },
    unsubscribe() {
      this.unsubscribeOfA!()
    }
  }
})
```

component
```html
<script setup lang="ts">
import { useTestStore } from '@/store/testStore'

const testStore = useTestStore()
const { a, b } = storeToRefs(testStore)
testStore.setup()
</script>

<template>
  <div>
    <div>
      {{ a }}
      {{ b }}
    </div>
    <button @click="testStore.unsubscribe">unsubscribe A</button>
  </div>
</template>

<style scoped>
/* css */
</style>
```

Change value, after the unsubscription, only one subscription was stopped
<img width="432" alt="日程調整のNitte" src="https://user-images.githubusercontent.com/6919381/187015488-3c2c0a40-b630-4a68-b3ff-56c21b3bb2ee.png">

So there are duplicate listeners, but I think it's expected behavior.

# Returning property
> sync can check this property before calling onSnapshot
Yes, this is good idea.
But, to return document data by `sync` method, we need to make `sync` function async.


So it might need a other async function that returns Unsubscribe and document data.
(PR is welcome)
